export const categories = [
    "action",
    "adventure",
    "animals",
    "comedy",
    "crime",
    "detective",
    "drama",
    "epic",
    "fables",
    "fairy-tales",
    "fantasy",
    "folklore",
    "friendship",
    "historical",
    "horror",
    "inspirational",
    "magical",
    "mystery",
    "post-apocalyptic",
    "romance",
    "science-fiction",
    "space",
    "sports",
    "supernatural",
    "survival",
    "thriller",
    "time-travel",
    "travel",
    "urban",
    "war",
    "western"
]

export const ages = [
    { key: "0-3", label: "0-3" },
    { key: "4-7", label: "4-7" },
    { key: "8-12", label: "8-12" },
    { key: "13-18", label: "13-18" },
    { key: "18-30", label: "18-30" },
    { key: "30+", label: "30+" },
];

export const pagesItem = [
    { key: "1", label: "1" },
    { key: "2", label: "2" },
    { key: "3", label: "3" },
    { key: "4", label: "4" },
    { key: "5", label: "5" },
    { key: "6", label: "6" },
];